#!/bin/bash
echo "🔐 NomadCoin Wallet Import Demonstration"
echo "======================================="
echo ""
echo "📋 Current State:"
echo "   • Wallet CLI only creates new addresses (no import yet)"
echo "   • GUI creates new addresses via '+ New Address' button"
echo "   • Private keys are shown when creating new wallets"
echo ""
echo "💡 Workflow for Using Existing Keys:"
echo ""
echo "1️⃣  Generate address with NomadCoin (to get format correct)"
echo "    ./releases/nomadcoin-macos-cli wallet --count 1"
echo ""
echo "2️⃣  Save the PRIVATE KEY shown in output (64 hex chars)"
echo ""
echo "3️⃣  When importing is available, use:"
echo "    ./releases/nomadcoin-macos-cli wallet import --private-key <your_key>"
echo ""
echo "4️⃣  Or use GUI import (planned)"
echo ""
echo "🔒 Security Notes:"
echo "   • Never share your private key"
echo "   • Backup wallet.dat if you have funds"
echo "   • Mobile apps will have seed phrase backup"
echo ""
echo "📱 Mobile First Design:"
echo "   • Create wallet on iOS/Android app"
echo "   • Use same address on desktop"
echo "   • Cross-platform by design"
echo ""
echo "✅ To get started RIGHT NOW:"
echo "   ./releases/nomadcoin-macos-cli wallet"
echo "   (Then use the address shown for mining/transactions)"
